### ISSUE TITLE
PVCs are not being provisioned

### ISSUE THREAD

**Issue by gerardo** [bsycorp/kind#21]
This is initially a question, while I create a repro for this issue.

What's the best way to create a PV/PVC pair? I'm doing:

```
kind: PersistentVolume
apiVersion: v1
metadata:
  name: test-volume
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi
  hostPath:
    path: /test-volume
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test-volume
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
```
then applying through `kubectl apply -f volume.yml`, and subsequently creating a pod that makes use of this claim I get:

```
Events:
  Type       Reason                Age                From                         Message
  ----       ------                ----               ----                         -------
  Normal     ExternalProvisioning  10s (x5 over 70s)  persistentvolume-controller  waiting for a volume to be created, either by external provisioner "k8s.io/minikube-hostpath" or manual
```

After reading the [volumes docs for Minikube](https://github.com/kubernetes/minikube/blob/master/docs/persistent_volumes.md), I tried to use `/data/test-volume` as hostPath instead, but it still doesn't work.

My initial hypothesis is that this is caused by the [storage-provisioner addon being disabled](https://github.com/bsycorp/kind/blob/8ece5574f2efcbaf648247a34359fdae513ab344/resources/setup.sh#L74). The minikube docs also [make a reference to the storage-provisioner](https://github.com/kubernetes/minikube/blob/master/docs/persistent_volumes.md#dynamic-provisioning-and-csi) as the mechanism to create these hostPath volumes.
