### ISSUE TITLE
How to enable feature gates?

### ISSUE THREAD

**Issue by erikgb** [bsycorp/kind#30]
I am trying to generate Java code from CustomResourceDefinition in a CI pipeline, using the [approach described](https://github.com/kubernetes-client/java/blob/master/docs/generate-model-from-third-party-resources.md) in kubernetes client java.

This image has proven extremly useful for all Kubernetes-related CI pipeline stuff, so I tried to use it here too. But it seems like the generate java client approach does not work - at least not with the prebuild `bsycorp:kind` images on Docker Hub.

The problem is that the CustomResourceDefinition does not seem to be published to the openapi specification in the kube-api-server. And that makes the initial extract of the custom resource API fail in my CI pipeline.

After digging a bit, I think the problem is releated to the `CustomResourcePublishOpenAPI` feature gate not being enabled. So my question is: How to enable it? Do I need to build my custom image, based on this image, or is there another way?

Any help is appreciated!

**Comment by nhoughto** [comment]
So feature gates seems like it is configured via `minikube` as per the docs - https://minikube.sigs.k8s.io/docs/handbook/config/#enabling-feature-gates

This isn't exposed at the moment, at the moment in `setup.sh` we call minikube with a bunch of options, not exposing any extra config:
```
minikube start --vm-driver=none --kubernetes-version $KUBERNETES_VERSION ...
```

So the change would be to add a `MINIKUBE_EXTRA_ARGS` variable, add it to the setup.sh and then in your custom build you can configure that variable to appropriately configure minikube with the feature gates.

Surprising that you need it though, since we are just using minikube defaults for the most part, i'd expect support for CRDs would be enable OTB, is this a Java client specific problem?

Either way happy to look at a PR, i'd be keen for you to see if it solves your problem before adding support since it seems like something that should just work =)

**Comment by erikgb** [comment]
@nhoughto: Yes, I also think it should just work. And no, this is not at Java client specific problem. I didn't get to the Java part without the CRD registered in the api server.

Here is an extract from my CI setup (using GitLab CI):
```yaml
extract-api:
  stage: prepare
  services:
    - name: bsycorp/kind:latest-1.16
      alias: localhost
  image:
    # FIXME: Create dedicated kubectl image?
    name: bsycorp/kind:latest-1.16
    entrypoint: [""]
  before_script:
    # Must export KUBECONFIG variable to not interfer with server kind, ad variables are also provided to service images
    - export KUBECONFIG=$CI_PROJECT_DIR/.kube/config
    - >
      until curl -s --fail http://localhost:10080/kubernetes-ready; do
        sleep 1;
      done
    - curl -s http://localhost:10080/config --create-dirs -o $KUBECONFIG
  script:
    - kubectl create namespace crds
    - kubectl create -n crds -f crds/crontab-v1.yml
    - kubectl get customresourcedefinitions
    - kubectl explain crontabs --recursive
````

A run with this setup results in the following output:
```shell
$ export KUBECONFIG=$CI_PROJECT_DIR/.kube/config
 $ until curl -s --fail http://localhost:10080/kubernetes-ready; do # collapsed multi-line command
 $ curl -s http://localhost:10080/config --create-dirs -o $KUBECONFIG
 $ kubectl create namespace crds
 namespace/crds created
 $ kubectl create -n crds -f crds/crontab-v1.yml
 customresourcedefinition.apiextensions.k8s.io/crontabs.stable.example.com created
 $ kubectl get customresourcedefinitions
 NAME                          CREATED AT
 crontabs.stable.example.com   2020-04-14T05:44:37Z
 $ kubectl explain crontabs --recursive
 error: Couldn't find resource for "stable.example.com/v1, Kind=CronTab"
 ERROR: Job failed: exit code 1
```

I haven't tested with minikube directly, but I probably should. Getting pampered with the kind image, and running everything with CI.... 😉 But I suspect that the "mini" nature of minikube leads to no feature gates being installed by default. If that is the case, would you consider to add some feature gates by default in kind, or rather not? In my case, adding `CustomResourcePublishOpenAPI` would make sense.
