### ISSUE TITLE
IO high when kind deploy in microk8s

### ISSUE THREAD

**Issue by njleon007** [bsycorp/kind#32]
Hi,
1. **Gitlab Kubernetes runner run gitlab-runner in microk8s(containerd)**
2. **Kind as a service for a job**
```
test_kind:
  services:
    - name: ci/kind:latest-1.14
  image: dtzar/helm-kubectl
  stage: test
  script:
    - >
      until curl -s --fail http://localhost:10080/kubernetes-ready; do
        sleep 1;
      done
    - wget http://localhost:10080/config
    - mkdir -p ~/.kube && cp config ~/.kube/config
    - kubectl get nodes
```

 3. **waiting kind to ready, api is ok, but kubectl give exception**
```
curl -s --fail http://localhost:10080/kubernetes-ready
echo $?
0
```
kubectl get nodes:
The connection to the server localhost:8443 was refused - did you specify the right host or port?

4.  **about 1min later, k8s is running, but high iowait cpu utilization of host k8s-cluster**
```
kubectl get nodes
NAME       STATUS   ROLES         AGE   VERSION
minikube   Ready    master,node   40d   v1.14.10
```
```
**iotop**
33866 be/4 root        0.00 B/s    0.00 B/s  0.00 % 99.99 % etcd --advertise-client-urls=https://172.30.99.1:2379 --cert-file=/var/~pshot-count=10000 --trusted-ca-file=/var/lib/minikube/certs/etcd/ca.crt
1021 be/3 root        0.00 B/s    0.00 B/s  0.00 % 81.48 % [jbd2/sda5-8]
```
when prepare k8s, find etcdserver: request timed out，I guess it's io issue.

Thanks for help , if some config can improve this performance.
